version: "3.7"

services:

  exchange_api_mock:
    build:
      context: .
      dockerfile: deployment/rates_mock.Dockerfile
    restart: on-failure:5
    networks:
      private_net:
        ipv4_address: 10.1.2.10

  actual_rate_api:
    build:
      context: .
      dockerfile: deployment/rates_actual.Dockerfile
    restart: on-failure:5
    environment:
      - SERVICE_URL=http://exchange_api_mock:8000/exchange_rates.json
    networks:
      private_net:
        ipv4_address: 10.1.2.11

  sys_api:
    build:
      context: .
      dockerfile: deployment/main_api.Dockerfile
    restart: on-failure:5
    environment:
      - SECRET_KEY=8064a8eb3e874abb895c17b686dffa4f
      - DEBUG=on
      - SQL_DEBUG=on
      - RATE_SERVICE_URLS=http://actual_rate_api:8000/actual_rates.json
      - DB_FILEPATH=/data/system_db.sqlite3
    ports:
      - 8000:8000
    volumes:
      - .data:/data
    networks:
      private_net:
        ipv4_address: 10.1.2.12

networks:
  private_net:
    ipam:
      driver: default
      config:
        - subnet: 10.1.2.0/24
