# Generated by Django 3.0.2 on 2020-02-01 19:03

import common.payment_api.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('wallet_id', models.TextField(default=common.payment_api.models.random_wallet_id, verbose_name='Wallet')),
                ('currency', models.TextField(choices=[('CAD', 'CAD'), ('CNY', 'CNY'), ('EUR', 'EUR'), ('USD', 'USD')], default='USD', verbose_name='Currency')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Balance')),
                ('city', models.TextField(default='', verbose_name='City')),
                ('country', models.TextField(default='', verbose_name='Country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'payment_wallet',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WalletOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.UUIDField(default=uuid.uuid4, verbose_name='Operation')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('receipt', models.BooleanField(default=True, verbose_name='Is receipt')),
                ('info', models.TextField(default='', verbose_name='Information')),
                ('currency', models.TextField(choices=[('CAD', 'CAD'), ('CNY', 'CNY'), ('EUR', 'EUR'), ('USD', 'USD')], default='USD', verbose_name='Currency')),
                ('rate', models.DecimalField(decimal_places=10, default=1, max_digits=12, verbose_name='Currency rate')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Amount')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Balance')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_api.Wallet')),
            ],
            options={
                'db_table': 'payment_wallet_operation',
            },
        ),
    ]
